language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - "sudo apt-get update -qq"
install: 
  - "sudo apt-get install -qq python-docutils libmilter-dev"
script: 
  - "make test"
  - "rst2html README.rst > /dev/null"
  - "rst2html CHANGELOG.rst > /dev/null"
