language: python
python:
  - "2.7"
install: 
  - "pip install --use-mirrors pytest-pep8 flexmock"
  - "apt-get install python-docutils"
script: 
  - "python setup.py test"
  - "rst2html README.rst > /dev/null"
